= Projeto Integrador: Programação Orientada a Objetos
Lista de Exercícios <victor.silva@professores.ibmec.edu.br>
:stem:
:toc: left
:toclevels: 3
:imagesdir: img
:figure-caption: Figura
:table-caption: Tabela
:listing-caption: Algoritmo
:xrefstyle: short
:sectnums:

:stylesheet: manual.css
:icons: font

<<<

== Introdução a Java

. Altere o programa `MeuPrograma` para imprimir uma mensagem diferente.
. Altere o programa `MeuPrograma` para imprimir duas linhas de texto usando duas linhas de código `System.out`.
. Sabendo que os caracteres `\n` representam uma quebra de linhas, imprima duas linhas de texto usando uma única linha de código `System.out`.
. Na empresa onde trabalhamos, há tabelas com o quanto foi gasto em cada mês. Para fechar o balanço do primeiro trimestre, precisamos somar o gasto total. Sabendo que, em janeiro, foram gastos R$15.000, em fevereiro, R$23.000 e em março, R$17.000, faça um programa que calcule e imprima o gasto total no trimeste.
. Adicione código (sem alterar as linhas que já existem) na classe anterior para imprimir a média mensal de gasto.
. Imprima todos os números de 150 a 300.
. Imprima a soma de 1 até 1000.
. Imprima todos os múltiplos de 3, entre 1 e 100.
. Imprima os fatoriais de 1 a 10.
. Imprima os primeiros números da série de Fibonacci até passar de 100. Considere que o primeiro número da série é 0 e o segundo é 1.
. Escreva um programa que, dada uma variável `x` com algum valor inteiro, recalcule `x` de tal forma que seja igual a `x / 2` se `x` for par, e `3 * x + 1` se `x` for ímpar. O programa deve parar quando `x` tiver o valor final de 1. Por exemplo, para `x = 13`, a saída será `40 -> 20 -> 10 -> 5 -> 16 -> 8 -> 4 -> 2 -> 1`. *Dica:* utilize a função `System.out.print` para imprimir um dado sem quebrar linha.
