= Projeto Integrador: Programação Orientada a Objetos
Lista de Exercícios <victor.silva@professores.ibmec.edu.br>
:stem:
:toc: left
:toclevels: 3
:imagesdir: img
:figure-caption: Figura
:table-caption: Tabela
:listing-caption: Algoritmo
:xrefstyle: short
:sectnums:

:stylesheet: manual.css
:icons: font

<<<

== Introdução a Java

. Altere o programa `MeuPrograma` para imprimir uma mensagem diferente.
. Altere o programa `MeuPrograma` para imprimir duas linhas de texto usando duas linhas de código `System.out`.
. Sabendo que os caracteres `\n` representam uma quebra de linhas, imprima duas linhas de texto usando uma única linha de código `System.out`.
. Na empresa onde trabalhamos, há tabelas com o quanto foi gasto em cada mês. Para fechar o balanço do primeiro trimestre, precisamos somar o gasto total. Sabendo que, em janeiro, foram gastos R$15.000, em fevereiro, R$23.000 e em março, R$17.000, faça um programa que calcule e imprima o gasto total no trimeste.
. Adicione código (sem alterar as linhas que já existem) na classe anterior para imprimir a média mensal de gasto.
. Imprima todos os números de 150 a 300.
. Imprima a soma de 1 até 1000.
. Imprima todos os múltiplos de 3, entre 1 e 100.
. Imprima os fatoriais de 1 a 10.
. Imprima os primeiros números da série de Fibonacci até passar de 100. Considere que o primeiro número da série é 1 e o segundo é 1.
. Escreva um programa que, dada uma variável `x` com algum valor inteiro, recalcule `x` de tal forma que seja igual a `x / 2` se `x` for par, e `3 * x + 1` se `x` for ímpar. O programa deve parar quando `x` tiver o valor final de 1. Por exemplo, para `x = 13`, a saída será `40 -> 20 -> 10 -> 5 -> 16 -> 8 -> 4 -> 2 -> 1`. *Dica:* utilize a função `System.out.print` para imprimir um dado sem quebrar linha.

== Classes e objetos em Java

. Crie uma fábrica de carros:

* Crie uma classe `Carro`, com os atributos `cor`, `modelo`, `velocidadeAtual`, `velocidadeMaxima`. Inicialize `velocidadeAtual` com o valor 0;
* Crie métodos:
    ** `ligar()`, que emite a mensagem "O carro está ligado";
    ** `acelerar(quantidade)`, que aumenta a velocidade atual no valor passado;
    ** `pegarMarcha()`, que retorna um número de -1 a 3 conforme a velocidade do carro:
        *** Abaixo de 0: -1
        *** Abaixo de 40: 1
        *** Abaixo de 80: 2
        *** Igual ou acima de 80: 3
* Crie uma classe `Motor`, com os atributos `potencia` e `tipo`, e inclua um Motor no Carro;
* Crie uma classe de teste e exercite as classes e os métodos criados.

. Modele uma conta. A ideia aqui é apenas modelar, isto é, só identifique que informações são importantes. Desenhe tudo o que uma `Conta` tem e tudo o que ela faz. Ela deve ter o nome do titular (`String`), o número (`int`), a agência (`String`), o saldo (`double`) e uma data de abertura (`String`). Além disso, ela deve fazer as seguintes ações: sacar, para retirar um valor do saldo; depositar, para adicionar um valor ao saldo; calcularRendimento, para devolver o rendimento mensal dessa conta.
. Transforme o modelo acima em uma classe Java. Teste-a, usando uma outra classe que tenha o `main`. Você deve criar a classe da conta com o nome `Conta`, mas pode nomear como quiser a classe de testes, contudo, ela deve possuir o método `main`. A classe Conta deve conter pelo menos os seguintes métodos:

* `sacar` recebe um `valor` como parâmetro e retira esse valor do saldo da conta. O valor não pode ser inferior a 0;
* `depositar` recebe um `valor` como parâmetro e adiciona esse valor ao saldo da conta;
* `calcularRendimento` não recebe parâmetro algum e devolve o valor do saldo multiplicado por 0.1.

. Crie um método `recuperarDadosParaImpressao()`, que não recebe parâmetro mas devolve o texto com todas as informações da nossa conta para efetuarmos a impressão. Veja que ela não imprime o texto na tela (não é responsabilidade da Conta, e sim do Programa que possui uma Conta instanciada).
. Ao invés de utilizar uma única `String` para representar a data de abertura da conta, crie uma outra classe, chamada `Data`. Ela possui três campos `int`, para dia, mês e ano. Faça com que sua conta passe a usá-la.
. Crie um método na classe `Data` que devolva o valor formatado da data, isto é, devolva uma String com `dia/mes/ano`.
. Em um novo projeto, crie uma classe `Fibonacci` que possui um método `calculaFibonacci(num)`. Considere a classe de teste abaixo, que deve imprimir a sequência de fibonacci até a sexta posição (1, 1, 2, 3, 5, 8). Resolva esse exercício de forma recursiva, ou seja, o método `calculaFibonacci` não pode ter nenhum loop, só pode chamar ele mesmo como método.

    class TestaFibo() {
        public static void main(String[] args) {
            Fibonacci fibo = new Fibonacci();
            for (int i = 1; i <= 6; i++) {
                int resultado = fibo.calculaFibonacci(i);
                System.out.println(resultado);
            }
        }
    }

== Introdução a UML: Diagrama de Classes

. Identifique e nomeie as classes conceituais no texto a seguir. Lembre-se de que as classes conceituais são entidades sobre as quais nos interessa armazenar alguma informação. Relacione uma ou mais dessas informações para cada classe identificada, não se preocupando em ser completo. Apenas pense em algumas delas como mecanismos para identificar as classes.

    As universidades do município de Sertãozinho Alegre são separadas em _campi_, e cada _campus_ é dividido em um ou mais departamentos (Letras, Matemática etc.). Um departamento é chefiado por um de seus professores, mas há casos em que esse cargo está vago. Não há acúmulo de chefia. Os professores podem estar alocados em um ou mais departamentos. Um departamento pode ser criado sem que haja professores alocados a ele. Um aluno pode estar matriculado em mais de uma universidade e pode frequentar mais de uma disciplina na mesma universidade. As universidades podem não ter alunos matriculados. Cada departamento tem seu conjunto específico de disciplinas (pelo menos uma). Cada disciplina pode ser ministrada por um ou mais professores. Cada professor pode ministrar qualquer número de disciplinas.

. Relacione e dê nomes adequados a alguns atributos que você imagina serem importantes para as classes identificadas no exercício anterior. Adote a notação da UML para formar rótulos completos de atributos. Use visibilidades, tipos, multiplicidades e valores default que julgar mais convenientes.
. Elabore o modelo conceitual de classes referente ao texto do primeiro exercício.
. Implemente em Java o projeto referente ao primeiro exercício.

== Arrays

. Crie uma classe `TestaArrays` e no método `main` crie um array de contas de tamanho 10. Em seguida, faça um loop para criar 10 contas com saldos distintos (por exemplo, multiplicando o índice do loop por 100 para gerar o saldo).
. Ainda na classe `TestaArrays`, faça outro loop para calcular e imprimir a média dos saldos de todas as contas do array.
. Crie uma classe `TestaSplit` que reescreva uma frase com as palavras na ordem invertida. "Socorram-me, subi no ônibus em Marrocos" deve retornar "Marrocos em ônibus no subi Socorram-me,". Utilize o método `split` da `Sprint` para te auxiliar. Esse método divide uma `String` de acordo com o separador especificado e devolve as partes em um array de `String`, por exemplo:

    String frase = "Uma mensagem qualquer";
    String[] palavras = frase.split();

    // Agora só basta percorrer o array na ordem inversa imprimindo as palavras

. No projeto desenvolvido em aula, crie um método para verificar se uma determinada `Conta` se encontra ou não como conta deste banco:

    public boolean contem(Conta conta) {
        // código
    }

. No projeto desenvolvido em aula, atualize o método `criarConta` para, caso todas as contas já tenham sido preenchidas, ele chame o método `expandir`, passando como argumento uma nova capacidade igual à capacidade anterior mais um, para só então criar a conta desejada.

== UML: Diagramas de Casos de Uso

. Identifique os atores de casos de uso de sistema para cada uma das situações a seguir.  Considere que as situações dizem respeito à especificação de três sistemas totalmente distintos entre si.
.. ...o atendente abre uma nova OS (ordem de serviço)...
.. ...o atendente abre uma nova OS e entrega uma cópia do relatório de abertura ao cliente que se encontra no balcão...
.. ...o atendente abre uma nova OS. Ao final do processo de abertura da OS o supervisor é informado por e-mail...

. Identifique os casos de uso de sistema para cada uma das situações a seguir. Considere que as situações dizem respeito à especificação de três sistemas totalmente distintos entre si.
.. O atendente informa a conclusão da OS...
.. (em um sistema de segurança computadorizado) ...o sensor de presença do sistema de segurança aciona o alarme que pode ser desligado pelo supervisor de segurança...

. Desenvolva os diagramas de casos de uso de sistema para as situações a seguir. Imagine que as situações são trechos de especificações de sistemas distintos.
.. O atendente informa ao sistema a conclusão das OS cujos dados são, então, passados ao Sistema de Contas a Receber (SCR), que efetuará a cobrança...
.. ...o atendente informa ao sistema a conclusão das OS. Uma cópia impressa do relatório de conclusão segue junto com o equipamento para o cliente e outra cópia vai para o setor de cobrança...
.. ...o atendente abre uma nova OS, informando os dados do cliente e do equipamento...
.. ...o atendente abre uma nova OS. Durante esse processo, o sistema solicita a definição dos campos de um formulário de cadastro de clientes. Esse mesmo formulário pode ser apresentado ao supervisor, para eventual alteração cadastral...
.. ...o atendente abre uma nova OS e, caso o cliente não esteja cadastrado, essa é a hora de fazê-lo. O atendente ou o supervisor podem, a qualquer momento, cadastrar novos clientes sem que estes solicitem qualquer serviço...
.. ...clientes do laboratório podem se cadastrar via Internet. O cadastro também pode ser feito na chegada do cliente, pela recepcionista, na abertura de uma lista de exames.
.. Às sextas-feiras, às 18h, o expediente para o público é encerrado e às 18h30min o sistema automaticamente imprime a relação de
inadimplentes...
.. ...o chefe do suporte é informado pela rotina de autenticação do sistema, via "torpedo", de qualquer pedido de autenticação feito pelos usuários cadastrados na lista negra de usuários.

. Esboce o diagrama e descreva o caso _Registrar Compra_ em um sistema para um supermercado hipotético, do qual participa o _Caixa_, registrando a compra, eventualmente o _Cliente_, quando o pagamento é feito por débito ou crédito no cartão e ele precisa informar a senha, além do _Supervisor de Vendas_, quando é necessário retirar um ou mais itens da lista compras ou reimprimi-la. Use sua vivência para estabelecer os passos que compõem a descrição, mas não se esqueça de considerar as situações em que:
.. Tudo dá certo;
.. Você não tem o dinheiro suficiente para pagar toda a compra, podendo perceber isso durante o registro ou ao final dele;
.. A fita de papel da máquina registradora acaba no meio da compra e o supervisor precisa intervir com seus "superpoderes" para comandar a
reimpressão da lista desde o início;
.. Você discorda do preço de um item que estava em oferta e pede ao caixa que retire o item da lista. Nesse caso, o supervisor também precisa intervir;
.. O código de barras não pôde ser lido pela leitora ótica e o caixa o informa pelo teclado;
.. O código do item não consta do cadastro;
.. Você paga em cartão com chip (no débito ou no crédito) ou em dinheiro, o que é bem menos frequente naquele supermercado.

== AS

=== Pedido

Desenvolva um sistema de gestor de salas, com a seguinte descrição:

----
Um programa gestor de salas deve poder cadastrar disciplinas e reservar salas para cada disciplina. Disciplinas são cadastradas com nome, código, dia da semana e sala. Salas são cadastradas com número e uma agenda. As salas podem ser salas de aula ou laboratórios. Laboratórios também devem cadastrar os equipamentos disponíveis.

Ao cadastrar uma disciplina, o gestor deve verificar a disponibilidade da sala para aquele dia da semana. Caso a sala não esteja disponível, o gestor não pode criar a disciplina.

O gestor deve implementar uma interface do sistema geral da empresa, para exportar as informações de disciplinas e salas para arquivos .txt. Disciplinas e salas devem ser salvas em arquivos separados. Os arquivos devem ser salvos na raiz do projeto.

As disciplinas devem ser armazenadas no seguinte formato:

<codigo>;<nome>;<dia-semana>;<sala>

As salas devem ser armazenadas no seguinte formato:

<número>;<disc-segunda>;<disc-terça>;<disc-quarta>;<disc-quinta>;<disc-sexta>;<equipamentos>

Caso não haja uma disciplina reservada naquele dia, o campo deve ser deixado em branco. Os equipamentos devem ser separados por vírgula.

O programa deve possuir uma interface de texto para operar o sistema.
----

A interface do sistema geral da empresa possui o seguinte código (que deve ser incluído no sistema a ser desenvolvido):

----
public interface IExportadorDados {
    void exportaDados(ArrayList<Disciplina> disciplinas, ArrayList<Sala> salas) throws IOException;
}
----

De posse dos requisitos apresentados acima, desenvolva uma aplicação em Java que atenda a todos os requisitos apresentados. Elabore também um diagrama de classes que represente o projeto desenvolvido.

=== Dicas

. Para a agenda da sala, use um array de `Disciplina` com 5 elementos. A posicao do array indica o dia da semana em que a disciplina está reservada. Um valor `null` em um determinado elemento do array indica que a sala está disponível naquele dia.
. Utilize o modelo do trabalho disponível, fazendo um fork do projeto para a sua conta no GitHub.

=== Fazendo um fork no GitHub

. Faça login na sua conta;
. Acesse a página do repositório modelo (https://github.com/victor0machado/2021.1-progoo-as);
. No canto superior direito, clique em "Fork" (canto superior direito da tela);
. Quando o GitHub terminar de executar o fork, você vai ter uma cópia do repositório na sua conta;
. Na tela que aparecer, clique em "Settings";
. Na tela que aparecer, vá até o final da página e clique em "Change visibility";
. Clique na opção "Make private" e confirme;
. Ainda na página de "Settings", clique na opção "Manage access", na barra lateral esquerda;
. Na tela que aparecer, clique em "Invite a collaborator" e inclua o meu usuário (victor0machado);
. Faça o clone do repositório no seu computador e proceda com a implementação normalmente.

*Fazer o fork corretamente, abrir um novo branch de trabalho e submeter um pull request corretamente será considerado um bônus de 1,0 ponto.*

Caso não deseje fazer o fork e submeter o projeto pelo GitHub, faça um .zip do seu código e submeta o conteúdo pelo Teams.
