= Projeto Integrador: Programação Orientada a Objetos
Lista de Exercícios <victor.silva@professores.ibmec.edu.br>
:stem:
:toc: left
:toclevels: 3
:imagesdir: img
:figure-caption: Figura
:table-caption: Tabela
:listing-caption: Algoritmo
:xrefstyle: short
:sectnums:

:stylesheet: manual.css
:icons: font

<<<

== Introdução a Java

. Altere o programa `MeuPrograma` para imprimir uma mensagem diferente.
. Altere o programa `MeuPrograma` para imprimir duas linhas de texto usando duas linhas de código `System.out`.
. Sabendo que os caracteres `\n` representam uma quebra de linhas, imprima duas linhas de texto usando uma única linha de código `System.out`.
. Na empresa onde trabalhamos, há tabelas com o quanto foi gasto em cada mês. Para fechar o balanço do primeiro trimestre, precisamos somar o gasto total. Sabendo que, em janeiro, foram gastos R$15.000, em fevereiro, R$23.000 e em março, R$17.000, faça um programa que calcule e imprima o gasto total no trimeste.
. Adicione código (sem alterar as linhas que já existem) na classe anterior para imprimir a média mensal de gasto.
. Imprima todos os números de 150 a 300.
. Imprima a soma de 1 até 1000.
. Imprima todos os múltiplos de 3, entre 1 e 100.
. Imprima os fatoriais de 1 a 10.
. Imprima os primeiros números da série de Fibonacci até passar de 100. Considere que o primeiro número da série é 1 e o segundo é 1.
. Escreva um programa que, dada uma variável `x` com algum valor inteiro, recalcule `x` de tal forma que seja igual a `x / 2` se `x` for par, e `3 * x + 1` se `x` for ímpar. O programa deve parar quando `x` tiver o valor final de 1. Por exemplo, para `x = 13`, a saída será `40 -> 20 -> 10 -> 5 -> 16 -> 8 -> 4 -> 2 -> 1`. *Dica:* utilize a função `System.out.print` para imprimir um dado sem quebrar linha.

== Classes e objetos em Java

. Crie uma fábrica de carros:

* Crie uma classe `Carro`, com os atributos `cor`, `modelo`, `velocidadeAtual`, `velocidadeMaxima`. Inicialize `velocidadeAtual` com o valor 0;
* Crie métodos:
    ** `ligar()`, que emite a mensagem "O carro está ligado";
    ** `acelerar(quantidade)`, que aumenta a velocidade atual no valor passado;
    ** `pegarMarcha()`, que retorna um número de -1 a 3 conforme a velocidade do carro:
        *** Abaixo de 0: -1
        *** Abaixo de 40: 1
        *** Abaixo de 80: 2
        *** Igual ou acima de 80: 3
* Crie uma classe `Motor`, com os atributos `potencia` e `tipo`, e inclua um Motor no Carro;
* Crie uma classe de teste e exercite as classes e os métodos criados.

. Modele uma conta. A ideia aqui é apenas modelar, isto é, só identifique que informações são importantes. Desenhe tudo o que uma `Conta` tem e tudo o que ela faz. Ela deve ter o nome do titular (`String`), o número (`int`), a agência (`String`), o saldo (`double`) e uma data de abertura (`String`). Além disso, ela deve fazer as seguintes ações: sacar, para retirar um valor do saldo; depositar, para adicionar um valor ao saldo; calcularRendimento, para devolver o rendimento mensal dessa conta.
. Transforme o modelo acima em uma classe Java. Teste-a, usando uma outra classe que tenha o `main`. Você deve criar a classe da conta com o nome `Conta`, mas pode nomear como quiser a classe de testes, contudo, ela deve possuir o método `main`. A classe Conta deve conter pelo menos os seguintes métodos:

* `sacar` recebe um `valor` como parâmetro e retira esse valor do saldo da conta. O valor não pode ser inferior a 0;
* `depositar` recebe um `valor` como parâmetro e adiciona esse valor ao saldo da conta;
* `calcularRendimento` não recebe parâmetro algum e devolve o valor do saldo multiplicado por 0.1.

. Crie um método `recuperarDadosParaImpressao()`, que não recebe parâmetro mas devolve o texto com todas as informações da nossa conta para efetuarmos a impressão. Veja que ela não imprime o texto na tela (não é responsabilidade da Conta, e sim do Programa que possui uma Conta instanciada).
. Ao invés de utilizar uma única `String` para representar a data de abertura da conta, crie uma outra classe, chamada `Data`. Ela possui três campos `int`, para dia, mês e ano. Faça com que sua conta passe a usá-la.
. Crie um método na classe `Data` que devolva o valor formatado da data, isto é, devolva uma String com `dia/mes/ano`.
. Em um novo projeto, crie uma classe `Fibonacci` que possui um método `calculaFibonacci(num)`. Considere a classe de teste abaixo, que deve imprimir a sequência de fibonacci até a sexta posição (1, 1, 2, 3, 5, 8). Resolva esse exercício de forma recursiva, ou seja, o método `calculaFibonacci` não pode ter nenhum loop, só pode chamar ele mesmo como método.

    class TestaFibo() {
        public static void main(String[] args) {
            Fibonacci fibo = new Fibonacci();
            for (int i = 1; i <= 6; i++) {
                int resultado = fibo.calculaFibonacci(i);
                System.out.println(resultado);
            }
        }
    }

== Introdução a UML: Diagrama de Classes

. Identifique e nomeie as classes conceituais no texto a seguir. Lembre-se de que as classes conceituais são entidades sobre as quais nos interessa armazenar alguma informação. Relacione uma ou mais dessas informações para cada classe identificada, não se preocupando em ser completo. Apenas pense em algumas delas como mecanismos para identificar as classes.

    As universidades do município de Sertãozinho Alegre são separadas em _campi_, e cada _campus_ é dividido em um ou mais departamentos (Letras, Matemática etc.). Um departamento é chefiado por um de seus professores, mas há casos em que esse cargo está vago. Não há acúmulo de chefia. Os professores podem estar alocados em um ou mais departamentos. Um departamento pode ser criado sem que haja professores alocados a ele. Um aluno pode estar matriculado em mais de uma universidade e pode frequentar mais de uma disciplina na mesma universidade. As universidades podem não ter alunos matriculados. Cada departamento tem seu conjunto específico de disciplinas (pelo menos uma). Cada disciplina pode ser ministrada por um ou mais professores. Cada professor pode ministrar qualquer número de disciplinas.

. Relacione e dê nomes adequados a alguns atributos que você imagina serem importantes para as classes identificadas no exercício anterior. Adote a notação da UML para formar rótulos completos de atributos. Use visibilidades, tipos, multiplicidades e valores default que julgar mais convenientes.
. Elabore o modelo conceitual de classes referente ao texto do primeiro exercício.
. Implemente em Java o projeto referente ao primeiro exercício.
